/**
 * 
 */
package mayday.vis3.export.filters;

import java.awt.Color;
import java.awt.Component;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.HashMap;

import javax.xml.parsers.DocumentBuilderFactory;

import mayday.core.MaydayDefaults;
import mayday.core.pluma.PluginInfo;
import mayday.core.pluma.PluginManagerException;
import mayday.vis3.export.ExportPlugin;
import mayday.vis3.export.ExportSetting;

import org.apache.batik.svggen.SVGGeneratorContext;
import org.apache.batik.svggen.SVGGraphics2D;
import org.w3c.dom.Document;

public class ExportSVG extends ExportPlugin {

	@Override
	public String getFormatName() {
		return "SVG";
	}

	@Override
	public void exportComponent(Component plotComponent, ExportSetting settings)
			throws Exception {
		// create a new DOM document
		Document l_document = DocumentBuilderFactory.newInstance().newDocumentBuilder().newDocument();

		// create a context for the SVG renderer
		SVGGeneratorContext l_context = SVGGeneratorContext.createDefault( l_document );
		l_context.setComment( " Generated by " +
				MaydayDefaults.PROGRAM_FULL_NAME +
		" using Apache Batik SVG Generator. " );
		l_context.setEmbeddedFontsOn( true );

		// create SVG renderer    
		SVGGraphics2D l_SVGGenerator = new SVGGraphics2D( l_context, false );

		l_SVGGenerator.setBackground( Color.white );
		//l_SVGGenerator.setClip(0,0,width,height);
		l_SVGGenerator.setSVGCanvasSize(settings.getDimension());
		
		exportComponentToCanvas(plotComponent, l_SVGGenerator, settings);
		
		FileOutputStream l_FileOutStream = new FileOutputStream(settings.getTargetFilename());
		OutputStreamWriter l_fileWriter = new  OutputStreamWriter(l_FileOutStream,"UTF-8"); // changed JD
		l_SVGGenerator.stream( l_fileWriter );
		l_fileWriter.close();    
		l_FileOutStream.close(); 		
	}

	@Override
	public void init() {		
	}

	@SuppressWarnings("unchecked")
	@Override
	public PluginInfo register() throws PluginManagerException {
		PluginInfo pli = new PluginInfo(
				(Class)this.getClass(),
				"PAS.vis3.export.svg",
				new String[]{},
				ExportPlugin.MC,
				new HashMap<String, Object>(),
				"Florian Battke",
				"battke@informatik.uni-tuebingen.de",
				"SVG Graphics Export Filter",
				"SVG"
		);
		return pli;	
	}
	
}